#!/usr/bin/env bash

# secret.pdf -> pdf är suffix (file extension)

file=secret.projectX.pdf

echo "$file"

# starts from beginning go to 1st . and removes everything before # -> non-greedy
echo "${file#*.}"
# greedy (2 hashes ##)
echo "${file##*.}"
# start from end, %=non greedy, %%=greedy
echo "${file%.*}"




# environment variable
echo "$PWD"

repo_path="${PWD%/*}"
echo "$repo_path"


repo_name="${repo_path##*/}"
echo "$repo_name"


