#!/usr/bin/env bash

age=$1
if [[ $age -ge 18 ]]; then
    echo "welcome to pub"
elif [[ $age -ge 13 ]]; then
	echo "you are teenager"
elif [[ $age -lt 13 ]]; then   
	echo "you are child"
fi

echo "Program continues here ..."

number=43
# compares '8' > '4'
if [[ $number -gt 42 ]]; then
    echo "$number > 42"
fi

