#!/usr/bin/env bash

echo "$PWD"
mkdir -p staging

# -m: monitor, -e: event 1, -e: event 2, --format "%f": endast filnamnet "$PWD": denna pathway/directory (för att ändra dir, t.ex. Hämtningar: "$PWD" ~/Hämtningar)

inotifywait -m -e close_write -e moved_to --format "%f" "$PWD" |  while
read -r filename; do
    echo "$filename"
    mv "$filename" staging/
done

