#!/usr/bin/env bash

age=$1
if [[ $age -ge 18 ]]; then
        echo "welcome to pub"
elif [[ $age -ge 13 ]]; then
	echo "you are teenager"
else    
	echo "you are child"
else
	echo "you are too young"
fi

